name: echo_map
description: "EchoMap is a vibration-only navigation app built in Flutter to empower blind and low-vision users to travel independently and confidently. By translating turn-by-turn directions into distinct haptic cues, EchoMap keeps you on the right path—no sight required."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  vibration: ^3.1.3

  google_maps_flutter: ^2.5.3
  flutter_polyline_points: ^2.0.0
  dio: ^5.4.0

  geolocator: ^14.0.1

  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  flutter_tts: ^3.8.3

  flutter_dotenv: ^5.1.0
  speech_to_text: ^7.0.0
  shake: ^3.0.0

  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^3.15.1
  firebase_analytics: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
